const loveNotes: string[] = [
  "I love how much you smile with your whole face",
  "I love your laugh",
  "I love your playful nature",
  "I love how your childish at heart",
  "You believe in me when I forget how to",
  "You're the best decision I've ever made",
  "You always know how to make me feel better",
  "Your kisses taste like heaven",
  "Your kisses feel like heaven",
  "Your hugs make me feel safe and warm",
  "Your laugh is my favourite melody",
  "You're incredibly selfless",
  "You are incredibly pretty despite what you and others might think",
  "You are nice to have around",
  "You never fail to make my day better, even without trying.",
  "The way you look at me makes me feel seen.",
  "You bring peace to my chaos.",
  "Loving you is the easiest thing I’ve ever done.",
  "You make life feel like a movie I never want to end.",
  "You believe in me even when I don’t.",
  "You make ordinary days feel magical.",
  "You're my favorite ‘what if’ turned reality.",
  "Even your silence is comforting.",
  "You make me want to be a better man every day.",
  "The way you talk about your dreams inspires me.",
  "I could spend forever just listening to your voice.",
  "You understand me in ways I never expected anyone would.",
  "You feel like home, even when we’re apart.",
  "Your voice notes are to die for; at least for me anyways",
  "I still get excited when I see your name pop up on my phone.",
  "You’re my calm in the storm, my peace in the chaos.",
  "You’re the best part of my favorite memories.",
  "You make me feel like the luckiest person alive without even knowing it.",
  "If I could relive any day, I’d choose a day with you. Every time.",
  "You turn the boring parts of life into something I want to relive.",
  "You always know what to say—even when you say nothing at all.",
  "Loving you has made me love life more.",
  "Loving you has made me forget what hate feels like",
  "When you’re happy, my whole world lights up.",
  "You’ve made me see the beauty in the little things.",
  "Your kindness is something I want to learn from every day.",
  "You make my heart feel safe, not just excited.",
  "Even your flaws are better than anything I ever thought I wanted.",
  "You’re the best thing I’ve built—no code required.",
  "I didn’t know what I was missing until I met you.",
  "You're not just my girl—you’re my muse, my Amira.",
  "I don’t say it enough, but I’m proud of the woman you are.",
  "You’re more than beautiful—you’re meaningful.",
  "I could write a thousand lines of code, but none of them would describe how much I love you.",
  "You’ve turned my ordinary into art.",
  "I don’t need a perfect day—just one with you in it.",
  "Your love and affection kicks my supposed depression in the ass",
  "I love how you always listen to me",
  "I love our late night calls",
  "I really like our flirty texts",
  "I like our 3:00 time together",
  "I love how we're basically in our own world when we talk to each other",
];

export default loveNotes;
